/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/app/assets/export": {
    /**
     * Export Asset
     * @description 导出资产。第一期仅预留入口，available 恒 False。
     */
    post: operations["export_asset_api_v1_app_assets_export_post"];
  };
  "/api/v1/app/assets/{asset_type}/versions": {
    /**
     * List Asset Versions
     * @description 资产历史版本列表，含 depends_on 与 diff。
     */
    get: operations["list_asset_versions_api_v1_app_assets__asset_type__versions_get"];
  };
  "/api/v1/app/bootstrap": {
    /**
     * Bootstrap
     * @description 启动装配：菜单 / 路由 / 任务入口 / 文案 / 功能开关。
     *
     * 前端启动只请求一次即可渲染首页。
     */
    get: operations["bootstrap_api_v1_app_bootstrap_get"];
  };
  "/api/v1/app/conversation/message": {
    /**
     * Send Message
     * @description 发送一轮消息，返回最短结论 + 显式告知 + 行为引导 + 管线卡。
     */
    post: operations["send_message_api_v1_app_conversation_message_post"];
  };
  "/api/v1/app/report/full-text": {
    /**
     * Get Report Full Text
     * @description 完整报告页正文。只读资产版本，不重新生成。
     */
    get: operations["get_report_full_text_api_v1_app_report_full_text_get"];
  };
  "/api/v1/app/sessions": {
    /**
     * List Sessions
     * @description 左栏会话列表（并行任务会话，按任务/环节命名）。
     */
    get: operations["list_sessions_api_v1_app_sessions_get"];
  };
  "/api/v1/app/task/enter": {
    /**
     * Enter Task
     * @description 从首页任务入口进入微循环。
     *
     * 编排器判定目标环节与主理；已存在进行中的同一任务时执行"续接"而非重建。
     */
    post: operations["enter_task_api_v1_app_task_enter_post"];
  };
  "/api/v1/app/track": {
    /**
     * Track Event
     * @description 前端上报一条埋点事件。
     */
    post: operations["track_event_api_v1_app_track_post"];
  };
  "/api/v1/app/workspace": {
    /**
     * Get Workspace
     * @description 工作台聚合视图：画像 / 报告 / 方案 / 计划 / 跟踪 + 功能块。
     *
     * 进入工作台属于持久化行为，游客在此处被登录拦截（PRD §5.3）。
     */
    get: operations["get_workspace_api_v1_app_workspace_get"];
  };
  "/healthz": {
    /** 装配健康检查 */
    get: operations["healthz_healthz_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AgentTheoryView
     * @description 智能体持有的理论卡（id + 中文名）。
     *
     * 只下发 id 与展示名：前端要显示的是"帕森斯 · 了解自我"这类中文名，而注册表里
     * `theory_packages` 存的是理论卡 id。**翻译放后端**，否则前端只能硬编码映射，
     * 或把 `parsons_self` 直接显示给用户。
     */
    AgentTheoryView: {
      /** Id */
      id: string;
      /**
       * Name
       * @description 理论中文名，如 帕森斯 · 了解自我
       */
      name: string;
    };
    /**
     * AgentView
     * @description 能力池条目（智能体小队页 / 工作台使用）。
     *
     * 口径（待决问题 D9）：
     * - `stages` 由后端用 `(agent_id, stage)` 逐环节探测产出契约得出，
     *   **不在注册表里新增字段**，也不由前端猜；
     * - `theories` 由后端把理论卡 id 翻成中文名；
     * - `no` / `shortName` / `theme` 属纯展示，由前端按顺序与名称派生，不进契约。
     */
    AgentView: {
      /**
       * Id
       * @description 稳定标识，取值见 AgentRole
       */
      id: string;
      /**
       * Name
       * @description 展示名，如 建档分析师
       */
      name: string;
      /**
       * Not To Do
       * @description 边界：不做什么
       */
      not_to_do?: string[];
      /**
       * Role Summary
       * @description 一句话职责
       * @default
       */
      role_summary?: string;
      /**
       * Stages
       * @description 负责的环节；空表示按需调用、不主理某一段
       */
      stages?: components["schemas"]["LoopStage"][];
      /** Theories */
      theories?: components["schemas"]["AgentTheoryView"][];
      /** Tools */
      tools?: string[];
    };
    /** ApiResponse[BootstrapView] */
    ApiResponse_BootstrapView_: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      data?: components["schemas"]["BootstrapView"] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /** ApiResponse[ConversationTurnView] */
    ApiResponse_ConversationTurnView_: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      data?: components["schemas"]["ConversationTurnView"] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /** ApiResponse[ExportResultView] */
    ApiResponse_ExportResultView_: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      data?: components["schemas"]["ExportResultView"] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /** ApiResponse[ReportFullTextView] */
    ApiResponse_ReportFullTextView_: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      data?: components["schemas"]["ReportFullTextView"] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /** ApiResponse[SessionListView] */
    ApiResponse_SessionListView_: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      data?: components["schemas"]["SessionListView"] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /** ApiResponse[TaskSessionView] */
    ApiResponse_TaskSessionView_: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      data?: components["schemas"]["TaskSessionView"] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /** ApiResponse[TrackEventAck] */
    ApiResponse_TrackEventAck_: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      data?: components["schemas"]["TrackEventAck"] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /** ApiResponse[WorkspacePageView] */
    ApiResponse_WorkspacePageView_: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      data?: components["schemas"]["WorkspacePageView"] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /** ApiResponse[list[AssetVersionView]] */
    ApiResponse_list_AssetVersionView__: {
      /** @default 0 */
      code?: components["schemas"]["ErrorCode"];
      /** Data */
      data?: components["schemas"]["AssetVersionView"][] | null;
      /**
       * Message
       * @default ok
       */
      message?: string;
      /**
       * Trace Id
       * @description 链路追踪 id，由 BFF 生成并回写 X-Trace-Id 响应头；日志排查用
       */
      trace_id?: string;
    };
    /**
     * AssetType
     * @description 资产类型。影响面传播的最小单位。
     * @enum {string}
     */
    AssetType: "report" | "direction_plan" | "action_plan";
    /**
     * AssetVersionView
     * @description 资产版本视图（R-API-005）。前端据此展示"v1→v2 的差异"。
     */
    AssetVersionView: {
      /** Asset Id */
      asset_id: string;
      asset_type: components["schemas"]["AssetType"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Depends On Profile Keys */
      depends_on_profile_keys?: string[];
      /** Diff From Previous */
      diff_from_previous?: string | null;
      /** Version */
      version: number;
    };
    /**
     * BannerView
     * @description 横幅 / 运营位（可上下线、可排序）。
     */
    BannerView: {
      /**
       * Action Label
       * @default
       */
      action_label?: string;
      /**
       * Action Route
       * @default
       */
      action_route?: string;
      /**
       * Body
       * @default
       */
      body?: string;
      /** Code */
      code: string;
      /** Title */
      title: string;
    };
    /**
     * BootstrapView
     * @description 启动装配视图。
     */
    BootstrapView: {
      /**
       * Agents
       * @description 能力池：五位主理的展示名 / 职责 / 负责环节 / 理论 / 工具 / 边界
       */
      agents?: components["schemas"]["AgentView"][];
      /**
       * App Name
       * @description 应用名，取自动态文案 app.name；为空表示文案包缺失
       * @default
       */
      app_name?: string;
      /**
       * Banners
       * @description 横幅 / 运营位
       */
      banners?: components["schemas"]["BannerView"][];
      /**
       * Copy Bundle
       * @description 文案包（key → text），前端按 key 取用，不从后端解析自然语言
       */
      copy_bundle?: {
        [key: string]: string;
      };
      /**
       * Faqs
       * @description 常见问题
       */
      faqs?: components["schemas"]["FaqView"][];
      /**
       * Feature Flags
       * @description 功能开关：导出/导师/演示等
       */
      feature_flags?: {
        [key: string]: boolean;
      };
      /**
       * Identity
       * @description 当前身份：role / nickname / avatar
       */
      identity?: {
        [key: string]: string;
      };
      /** Menus */
      menus?: components["schemas"]["MenuView"][];
      /** Routes */
      routes?: components["schemas"]["RouteView"][];
      /** Task Entries */
      task_entries?: components["schemas"]["TaskEntryView"][];
      /**
       * Trust Blocks
       * @description 信任区：第一条为主线，其余为可展开示例
       */
      trust_blocks?: components["schemas"]["TrustBlockView"][];
    };
    /**
     * ConversationMessageView
     * @description 对话气泡。
     */
    ConversationMessageView: {
      /** Agent Id */
      agent_id?: string | null;
      /** Agent Name */
      agent_name?: string | null;
      /** Created At */
      created_at?: string | null;
      /**
       * Role
       * @enum {string}
       */
      role: "agent" | "user" | "system";
      /** Text */
      text: string;
      /**
       * Theory Refs
       * @description 可点开的理论标签
       */
      theory_refs?: {
          [key: string]: unknown;
        }[];
    };
    /**
     * ConversationTurnView
     * @description 一轮回复的完整视图。
     *
     * 对应架构文档 §5 的调用链返回：最短结论 + 显式告知 + 行为引导 + 管线卡。
     */
    ConversationTurnView: {
      /**
       * Badge
       * @description 顶栏主理徽章：agent_id/name/依据
       */
      badge?: {
        [key: string]: unknown;
      };
      /**
       * Changed Assets
       * @description 本轮变化的资产版本，用于工作台刷新
       */
      changed_assets?: {
          [key: string]: unknown;
        }[];
      /**
       * Disclosure
       * @description 换主理/换理论/结论变化的显式告知行
       */
      disclosure?: {
        [key: string]: unknown;
      } | null;
      /**
       * Guide
       * @description 行为引导：question/options/task/reminder 四选一
       */
      guide?: {
        [key: string]: unknown;
      };
      /** Messages */
      messages?: components["schemas"]["ConversationMessageView"][];
      /** Pipeline Cards */
      pipeline_cards?: components["schemas"]["PipelineCardView"][];
      stage: components["schemas"]["LoopStage"];
      /** Task Id */
      task_id: string;
    };
    /**
     * DependencyEdgeView
     * @description 依赖可视化（FR-WB-005 简版）。
     */
    DependencyEdgeView: {
      /** From Asset */
      from_asset: string;
      /** To Asset */
      to_asset: string;
      /** Via Profile Keys */
      via_profile_keys?: string[];
    };
    /**
     * ErrorCode
     * @description 统一错误码。前端据此提示，不解析后端文案。
     * @enum {integer}
     */
    ErrorCode: 0 | 1001 | 1002 | 1003 | 1004 | 1005 | 1006 | 1007 | 1999;
    /**
     * ExportRequest
     * @description 导出请求。
     */
    ExportRequest: {
      asset_type: components["schemas"]["AssetType"];
      /**
       * Format
       * @default pdf
       * @enum {string}
       */
      format?: "pdf" | "docx";
    };
    /**
     * ExportResultView
     * @description 导出结果。第一期 available 恒 False，仅预留入口。
     */
    ExportResultView: {
      /**
       * Available
       * @default false
       */
      available?: boolean;
      /**
       * Message
       * @default 第一期仅预留导出入口
       */
      message?: string;
      /** Object Key */
      object_key?: string | null;
    };
    /**
     * FaqView
     * @description 常见问题。
     */
    FaqView: {
      /** Answer */
      answer: string;
      /** Code */
      code: string;
      /** Question */
      question: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * LoopStage
     * @description 轴 B · 服务微循环五环节。
     * @enum {string}
     */
    LoopStage: "collect" | "diagnose" | "decide" | "act" | "review";
    /**
     * MenuView
     * @description 顶层导航项。仅"首页 / 核心对话页 / 智能工作台"三条主线。
     */
    MenuView: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Route */
      route: string;
      /**
       * Sort Order
       * @default 0
       */
      sort_order?: number;
      /**
       * Visible
       * @default true
       */
      visible?: boolean;
    };
    /**
     * MessageRequest
     * @description 一轮用户输入。支持会话续接（R-API-003）。
     */
    MessageRequest: {
      /**
       * Client Msg Id
       * @description 前端幂等键
       */
      client_msg_id?: string | null;
      /** Message */
      message: string;
      /** Task Id */
      task_id: string;
    };
    /**
     * PipelineCardView
     * @description 右栏管线卡（①-⑤ 每环节一卡）。
     *
     * 三态：当前产出 / 可展开理论模型 / 可展开评价状态。
     */
    PipelineCardView: {
      /**
       * Active
       * @description 是否为当前环节，前端高亮
       * @default false
       */
      active?: boolean;
      /**
       * Current Output
       * @description 态①：当前产出摘要
       */
      current_output?: {
        [key: string]: unknown;
      } | null;
      /**
       * Evaluation
       * @description 态③：可展开的评价状态
       */
      evaluation?: {
        [key: string]: unknown;
      } | null;
      stage: components["schemas"]["LoopStage"];
      /**
       * Status
       * @default empty
       * @enum {string}
       */
      status?: "empty" | "in_progress" | "done";
      /**
       * Theory Models
       * @description 态②：可展开的理论模型
       */
      theory_models?: {
          [key: string]: unknown;
        }[];
      /** Title */
      title: string;
    };
    /**
     * ProfilePanelView
     * @description ① 画像状态：字段覆盖度 / 置信度 / 缺口 / 更新时间。
     */
    ProfilePanelView: {
      /**
       * Coverage
       * @description 字段覆盖度
       * @default 0
       */
      coverage?: number;
      /** Fields */
      fields?: {
          [key: string]: unknown;
        }[];
      /** Gaps */
      gaps?: {
          [key: string]: unknown;
        }[];
      /**
       * Overall Confidence
       * @default 0
       */
      overall_confidence?: number;
      /** Updated At */
      updated_at?: string | null;
    };
    /**
     * ReportFullTextView
     * @description 完整报告页正文（只读资产视图，不承载实时对话）。
     */
    ReportFullTextView: {
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Report Id */
      report_id: string;
      /**
       * Sections
       * @description 15 维全景 / 方案 / 行动计划 / 个人画像
       */
      sections?: {
          [key: string]: unknown;
        }[];
      /**
       * Toc
       * @description 左侧目录导航
       */
      toc?: {
          [key: string]: string;
        }[];
      /** Version */
      version: number;
    };
    /**
     * RouteView
     * @description 前端路由。
     */
    RouteView: {
      /**
       * Page Code
       * @description 页面锚点口径，如 screen-home / screen-conv
       */
      page_code: string;
      /** Path */
      path: string;
      /**
       * Require Login
       * @default false
       */
      require_login?: boolean;
      /**
       * Sort Order
       * @default 0
       */
      sort_order?: number;
    };
    /**
     * SessionListView
     * @description 左栏会话列表。
     */
    SessionListView: {
      /** Current Task Id */
      current_task_id?: string | null;
      /** Sessions */
      sessions?: components["schemas"]["TaskSessionView"][];
    };
    /**
     * StagePanelView
     * @description ②-⑤ 的节点卡。三态：当前评价 / 理论模型 / 历史 diff。
     */
    StagePanelView: {
      /**
       * Diff
       * @description 差异说明，如「因更新了 X，v1→v2 的变化」
       */
      diff?: string | null;
      /**
       * Evaluation
       * @default
       */
      evaluation?: string;
      stage: components["schemas"]["LoopStage"];
      /** Theory Models */
      theory_models?: {
          [key: string]: unknown;
        }[];
      /** Title */
      title: string;
      /** Updated At */
      updated_at?: string | null;
      /** Version */
      version?: number | null;
    };
    /**
     * TaskEnterRequest
     * @description 进入任务（FR-HOME-002）。task_code 取自 bootstrap 的任务入口。
     */
    TaskEnterRequest: {
      /** Task Code */
      task_code: string;
    };
    /**
     * TaskEntryView
     * @description 首页任务入口（FR-HOME-001）。文案必须用"用户自己的话"。
     */
    TaskEntryView: {
      /** Code */
      code: string;
      /** Label */
      label: string;
      /**
       * Lead Agent Name
       * @description 开场主理展示名
       */
      lead_agent_name?: string | null;
      /**
       * Sort Order
       * @default 0
       */
      sort_order?: number;
      /** @description 为空表示走「直接开聊」，由编排器判定入口 */
      target_stage?: components["schemas"]["LoopStage"] | null;
    };
    /**
     * TaskSessionView
     * @description 左栏会话项。按"任务/环节"命名，不按 agent 名排布（FR-CONV-003）。
     */
    TaskSessionView: {
      /** Last Active At */
      last_active_at?: string | null;
      /**
       * Lead Agent Name
       * @default
       */
      lead_agent_name?: string;
      /**
       * Progress
       * @description 闭环进度
       * @default 0
       */
      progress?: number;
      stage: components["schemas"]["LoopStage"];
      /**
       * Stage Label
       * @description 环节中文名，用于左栏命名
       */
      stage_label: string;
      /** @default active */
      status?: components["schemas"]["TaskStatus"];
      /** Task Id */
      task_id: string;
      /** Task Name */
      task_name: string;
    };
    /**
     * TaskStatus
     * @description 任务会话状态。
     * @enum {string}
     */
    TaskStatus: "active" | "paused" | "completed";
    /**
     * TrackEventAck
     * @description 上报确认。第一期只确认接收，不返回处理详情。
     */
    TrackEventAck: {
      /**
       * Accepted
       * @default true
       */
      accepted?: boolean;
      /** Event */
      event: string;
    };
    /**
     * TrackEventRequest
     * @description 一次前端埋点上报。
     */
    TrackEventRequest: {
      /**
       * Client Event Id
       * @description 前端幂等键，用于去重
       */
      client_event_id?: string | null;
      /**
       * Event
       * @description 事件名，来自 data/registry/track_events.json
       */
      event: string;
      /**
       * Payload
       * @description 事件属性
       */
      payload?: {
        [key: string]: unknown;
      };
    };
    /**
     * TrustBlockView
     * @description 信任背书块（FR-HOME-005）。只讲一条主线，可点开方法论示例。
     */
    TrustBlockView: {
      /**
       * Body
       * @default
       */
      body?: string;
      /** Code */
      code: string;
      /**
       * Expandable Ref
       * @description 可展开内容的引用键，空为纯文本
       * @default
       */
      expandable_ref?: string;
      /** Title */
      title: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * WorkspacePageView
     * @description 工作台聚合视图。
     */
    WorkspacePageView: {
      /** @description ④ 计划与日历 */
      action_panel?: components["schemas"]["StagePanelView"] | null;
      /**
       * Axis A Stage
       * @description 轴 A 阶段过滤依据（FR-WB-004）
       */
      axis_a_stage?: string | null;
      /**
       * Blocks
       * @description 功能块入口与静态数据（FR-WB-007）
       */
      blocks?: {
        [key: string]: unknown;
      };
      /**
       * Coach Messages
       * @description 教练消息汇总（FR-WB-006）
       */
      coach_messages?: {
          [key: string]: unknown;
        }[];
      /** Dependencies */
      dependencies?: components["schemas"]["DependencyEdgeView"][];
      /** @description ③ 方案 */
      plan_panel?: components["schemas"]["StagePanelView"] | null;
      profile_panel?: components["schemas"]["ProfilePanelView"];
      /** @description ② 诊断与报告 */
      report_panel?: components["schemas"]["StagePanelView"] | null;
      /** @description ⑤ 跟踪与预警 */
      review_panel?: components["schemas"]["StagePanelView"] | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Export Asset
   * @description 导出资产。第一期仅预留入口，available 恒 False。
   */
  export_asset_api_v1_app_assets_export_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_ExportResultView_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Asset Versions
   * @description 资产历史版本列表，含 depends_on 与 diff。
   */
  list_asset_versions_api_v1_app_assets__asset_type__versions_get: {
    parameters: {
      path: {
        asset_type: components["schemas"]["AssetType"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_list_AssetVersionView__"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Bootstrap
   * @description 启动装配：菜单 / 路由 / 任务入口 / 文案 / 功能开关。
   *
   * 前端启动只请求一次即可渲染首页。
   */
  bootstrap_api_v1_app_bootstrap_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_BootstrapView_"];
        };
      };
    };
  };
  /**
   * Send Message
   * @description 发送一轮消息，返回最短结论 + 显式告知 + 行为引导 + 管线卡。
   */
  send_message_api_v1_app_conversation_message_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_ConversationTurnView_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Report Full Text
   * @description 完整报告页正文。只读资产版本，不重新生成。
   */
  get_report_full_text_api_v1_app_report_full_text_get: {
    parameters: {
      query?: {
        version?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_ReportFullTextView_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Sessions
   * @description 左栏会话列表（并行任务会话，按任务/环节命名）。
   */
  list_sessions_api_v1_app_sessions_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_SessionListView_"];
        };
      };
    };
  };
  /**
   * Enter Task
   * @description 从首页任务入口进入微循环。
   *
   * 编排器判定目标环节与主理；已存在进行中的同一任务时执行"续接"而非重建。
   */
  enter_task_api_v1_app_task_enter_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskEnterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_TaskSessionView_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Track Event
   * @description 前端上报一条埋点事件。
   */
  track_event_api_v1_app_track_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TrackEventRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_TrackEventAck_"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Workspace
   * @description 工作台聚合视图：画像 / 报告 / 方案 / 计划 / 跟踪 + 功能块。
   *
   * 进入工作台属于持久化行为，游客在此处被登录拦截（PRD §5.3）。
   */
  get_workspace_api_v1_app_workspace_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse_WorkspacePageView_"];
        };
      };
    };
  };
  /** 装配健康检查 */
  healthz_healthz_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
